
package my.example.ws.client.jaxws;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://ws.example.my/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.AddResponse")
    @Action(input = "http://ws.example.my/Calculator/addRequest", output = "http://ws.example.my/Calculator/addResponse")
    public BigDecimal add(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BigDecimal arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns my.example.ws.client.jaxws.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.GetResponse")
    @Action(input = "http://ws.example.my/Calculator/getRequest", output = "http://ws.example.my/Calculator/getResponse")
    public Person get(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.UpdateResponse")
    @Action(input = "http://ws.example.my/Calculator/updateRequest", output = "http://ws.example.my/Calculator/updateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.DeleteResponse")
    @Action(input = "http://ws.example.my/Calculator/deleteRequest", output = "http://ws.example.my/Calculator/deleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.CreateResponse")
    @Action(input = "http://ws.example.my/Calculator/createRequest", output = "http://ws.example.my/Calculator/createResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<my.example.ws.client.jaxws.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.SearchResponse")
    @Action(input = "http://ws.example.my/Calculator/searchRequest", output = "http://ws.example.my/Calculator/searchResponse")
    public List<Person> search(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
