
package my.example.ws.client.jaxws;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://ws.example.my/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.example.my/", className = "my.example.ws.client.jaxws.AddResponse")
    @Action(input = "http://ws.example.my/Calculator/addRequest", output = "http://ws.example.my/Calculator/addResponse")
    public BigDecimal add(
        @WebParam(name = "arg0", targetNamespace = "")
        BigDecimal arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        BigDecimal arg1);

}
